# Generated by Django 2.2.3 on 2019-07-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20190730_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sections', to='Shop.Type', verbose_name='Тип'),
        ),
    ]
