# Generated by Django 2.2.3 on 2019-07-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20190730_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='item_photos/', verbose_name='Изображение'),
        ),
    ]
