# Generated by Django 2.2.1 on 2019-08-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20190829_2145'),
        ('Shop', '0006_auto_20190730_2152'),
    ]

    operations = [
    ]
